version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
    - aws --version
    - AWS_ACCOUNT_ID=116088010194
    - AWS_DEFAULT_REGION=ap-south-1
    - S3_BUCKET_NAME=vibhu-client
    - S3_BUCKET_URI=s3://$S3_BUCKET_NAME
  build:
    commands:
      - echo install project dependencies 
      - npm install --only=production
      - echo invoke build
      - npm run build
  post_build:
    commands:
    - echo Build completed on `date` 
    - echo pushing to s3
    - aws s3 rm $S3_BUCKET_URI --recursive
    - aws s3 cp  --recursive --acl public-read ./build $S3_BUCKET_URI
    - echo Pushed all code to S3, completed on `date` 